name: production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: production
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_PORT: ${{ secrets.PORT }}
        envkey_DB_URL: ${{ secrets.DB_URL }}
        envkey_USER_TOKEN_SECRET: ${{ secrets.USER_TOKEN_SECRET }}
        envkey_USER_REFRESH_TOKEN_SECRET: ${{ secrets.USER_REFRESH_TOKEN_SECRET }}
        envkey_YTB_API_URL: ${{ secrets.YTB_API_URL }}
        envkey_YTB_API_KEY: ${{ secrets.YTB_API_KEY }}
        file_name: .env
        fail_on_empty: true
    - name: Build dependencies
      run: |
        npm install
    - name: Run server
      run: |
        echo "Auto test success, server on ${{ secrets.PORT }}"
